name: Mirroring

on:
  push:
    branches-ignore:
      - 'debug-*'

env:
  REPO_URL: "git@github.com:EpitechPromo2025/B-PSU-402-NAN-4-1-ftrace-nathan.rousseau.git"

jobs:
  check_make:
    name: Make all
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - run: make
        timeout-minutes: 5
  
  tests_run:
    name: tests_run
    runs-on: ubuntu-latest
    needs: [check_make]
    container: epitechcontent/epitest-docker:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: make tests_run
        timeout-minutes: 5

  push_to_mirror:
    name: Push to the repository
    runs-on: ubuntu-latest
    needs: [check_make]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Push
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.REPO_URL }}
          ssh_private_key:
            ${{ secrets.PUBLIC_SSH }}